name: Build Windows EXE (PyInstaller, Python 3.8, x86/x64)

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86, x64]
    env:
      PY_VER: '3.8'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PY_VER }} (${{ matrix.arch }})
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}
          architecture: ${{ matrix.arch }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          # 安装运行所需依赖
          if (Test-Path requirements.txt) { pip install -r requirements.txt } else { pip install requests==2.31.0 }

      - name: Prepare ffmpeg binaries (x64)
        if: matrix.arch == 'x64'
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          choco install ffmpeg -y
          New-Item -ItemType Directory -Force -Path ffmpeg\bin | Out-Null
          $ff = Get-Command ffmpeg.exe | Select-Object -First 1
          $fp = Get-Command ffprobe.exe | Select-Object -First 1
          if (-not $ff -or -not $fp) { throw '未找到 ffmpeg/ffprobe（x64）' }
          Copy-Item $ff.Source -Destination ffmpeg\bin\ffmpeg.exe -Force
          Copy-Item $fp.Source -Destination ffmpeg\bin\ffprobe.exe -Force
          Write-Host "Copied:" (Get-Item ffmpeg\bin\ffmpeg.exe).FullName
          Write-Host "Copied:" (Get-Item ffmpeg\bin\ffprobe.exe).FullName

      - name: Prepare ffmpeg binaries (x86)
        if: matrix.arch == 'x86'
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          New-Item -ItemType Directory -Force -Path ffmpeg\bin | Out-Null
          $zipUrl = 'https://github.com/sudo-nautilus/FFmpeg-Builds-Win32/releases/download/latest/ffmpeg-master-latest-win32-gpl-shared.zip'
          Invoke-WebRequest -Uri $zipUrl -OutFile ffmpeg32.zip
          Expand-Archive -Path ffmpeg32.zip -DestinationPath ffmpegtmp32 -Force
          # 查找 ffmpeg.exe 所在目录
          $ffItem = Get-ChildItem -Recurse -Path ffmpegtmp32 -Filter ffmpeg.exe | Select-Object -First 1
          if (-not $ffItem) { throw '在压缩包中未找到 ffmpeg.exe（x86）' }
          $binDir = $ffItem.Directory.FullName
          # 复制 exe 和依赖 dll（shared 构建需要 dll）
          Copy-Item (Join-Path $binDir 'ffmpeg.exe') -Destination ffmpeg\bin\ffmpeg.exe -Force
          $fpItem = Get-ChildItem -Recurse -Path ffmpegtmp32 -Filter ffprobe.exe | Select-Object -First 1
          if ($fpItem) { Copy-Item $fpItem.FullName -Destination ffmpeg\bin\ffprobe.exe -Force }
          Get-ChildItem -Path $binDir -Filter *.dll -ErrorAction SilentlyContinue | ForEach-Object {
            Copy-Item $_.FullName -Destination ffmpeg\bin -Force
          }
          Write-Host "Prepared x86 ffmpeg in:" (Resolve-Path ffmpeg\bin)

      - name: Build EXE with PyInstaller
        shell: pwsh
        run: |
          pyinstaller --onefile `
            --name BiliMusic-${{ matrix.arch }}-py${{ env.PY_VER }} `
            --runtime-hook hooks\rthook_meipass_path.py `
            --add-binary "ffmpeg\bin\ffmpeg.exe;." `
            --add-binary "ffmpeg\bin\ffprobe.exe;." `
            2.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BiliMusic-${{ matrix.arch }}-py${{ env.PY_VER }}
          path: |
            dist\BiliMusic-${{ matrix.arch }}-py${{ env.PY_VER }}.exe
            BiliMusic.spec
